#!/usr/bin/python3
"""
Factorize as many numbers as possible into a product of two smaller numbers.
"""
# library to get arguments
import sys


# fn unpack number factorial
def fc():
    """
    function fc to search file to convert number and format n=p*q
    """
    try:
        revfile = sys.argv[1]
        with open(revfile) as f:
            for revnumber in f:
                revnumber = int(revnumber)
                if revnumber % 2 == 0:
                        print("{}={}*{}".format(revnumber, revnumber // 2, 2))
                        continue
                z = 3
                while z < revnumber // 2:
                    if revnumber % z == 0:
                        print("{}={}*{}".format(revnumber, revnumber // z, z))
                        break
                    z = z + 2
                if z == (revnumber // 2) + 1:
                    print("{}={}*{}".format(revnumber, revnumber, 1))
    except (IndexError):
        pass


fc()
